##############################################################################
# Agent Hub infrastructure monitoring — cross-account read-only role.
#
# Apply this in the account you want Agent Hub to monitor. It creates a role
# Agent Hub assumes, gated on an external ID that Agent Hub generated for your
# project — copy it from the project's AWS settings module and do not invent
# one, because a value the caller can choose defends against nothing.
#
# The permission policy is `agent-hub-monitoring-policy.json` next to this
# file, read verbatim rather than restated, so the JSON is the single source of
# truth across all three formats published here.
##############################################################################

variable "agent_hub_account_id" {
  description = "AWS account the Agent Hub deployment runs in."
  type        = string
}

variable "agent_hub_collector_role_arn" {
  description = <<-EOT
    Role ARN Agent Hub assumes from. Pin the trust to this one principal rather
    than the whole account: `Principal = { AWS = "<account>" }` on its own
    trusts every user and role in that account.

    Use the role ARN, never the assumed-role session ARN — `aws:PrincipalArn`
    reports the role for an assumed session.
  EOT
  type        = string
}

variable "agent_hub_external_id" {
  description = <<-EOT
    External ID from the project's AWS settings module in Agent Hub. Unique per
    project, generated by the Hub, not editable. Not a secret: anyone who can
    read the role can read this condition. Its job is uniqueness per tenant, so
    one customer's role ARN cannot be monitored under another's project.
  EOT
  type        = string
}

variable "role_name" {
  type    = string
  default = "AgentHubMonitoring"
}

data "aws_iam_policy_document" "agent_hub_monitoring_trust" {
  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRole"]

    principals {
      type        = "AWS"
      identifiers = [var.agent_hub_collector_role_arn]
    }

    # StringEquals, never StringEqualsIfExists: the ...IfExists operators
    # evaluate true when the key is absent, which would let an AssumeRole call
    # that supplies no external ID through — reinstating exactly the
    # confused-deputy hole this condition exists to close.
    condition {
      test     = "StringEquals"
      variable = "sts:ExternalId"
      values   = [var.agent_hub_external_id]
    }

    # Defense in depth behind the principal above. AWS recommends ARN operators
    # over string operators when comparing ARNs.
    condition {
      test     = "ArnEquals"
      variable = "aws:PrincipalArn"
      values   = [var.agent_hub_collector_role_arn]
    }
  }
}

resource "aws_iam_role" "agent_hub_monitoring" {
  name                 = var.role_name
  description          = "Read-only telemetry access for Agent Hub infrastructure monitoring."
  assume_role_policy   = data.aws_iam_policy_document.agent_hub_monitoring_trust.json
  max_session_duration = 3600
}

resource "aws_iam_policy" "agent_hub_monitoring" {
  name        = "${var.role_name}ReadOnly"
  description = "Metadata and metric reads Agent Hub collectors call. No data-plane reads."
  policy      = file("${path.module}/agent-hub-monitoring-policy.json")
}

resource "aws_iam_role_policy_attachment" "agent_hub_monitoring" {
  role       = aws_iam_role.agent_hub_monitoring.name
  policy_arn = aws_iam_policy.agent_hub_monitoring.arn
}

output "agent_hub_monitoring_role_arn" {
  description = "Paste this into the project's assume-role AWS profile in Agent Hub."
  value       = aws_iam_role.agent_hub_monitoring.arn
}
