/**
 * `.env.preview` renderer for PR preview environments (W2).
 *
 * Takes a strongly-typed set of values and writes a `.env` file that the
 * container's app picks up. Interpolation is whitelist-driven — any
 * placeholder in the template that isn't in the provided value map is a
 * hard error. This keeps drift obvious: if we add a new `${VAR}` to the
 * template but forget to thread the value through, `buildPrEnvFile`
 * throws rather than silently emitting `VAR=` and letting the container
 * start in a broken state.
 *
 * Placeholders use `${NAME}` (shell-style) rather than Handlebars-style
 * `{{ name }}` so the template is readable as a real env file.
 */

/** Variables required by every PR-env invocation. */
export interface PrEnvTemplateValues {
  /** Short repo slug, e.g. "Speakman-ai/agent-hub". */
  repoFullName: string;
  /** PR number the env belongs to. */
  prNumber: number;
  /** Slot id the dispatcher bound (e.g. "pr-3"). */
  slotId: string;
  /** Host port assigned from the port pool. */
  hostPort: number;
  /** Absolute path to the per-PR SQLite copy (e.g. "/var/data/pr-123.db"). */
  dbPath: string;
  /** Sandbox GitHub App id — used so the PR env can call the GitHub API as our bot. */
  githubAppId: string;
  /** Sandbox GitHub App installation id for the repo. */
  githubInstallationId: string;
  /**
   * Sandbox GitHub App private key (PEM). Multiline; callers pass the raw
   * PEM — `renderEnvFile` escapes newlines so the env file stays a single
   * line per key (dotenv convention).
   */
  githubPrivateKey: string;
  /** Public preview URL, e.g. "https://pr-123.preview.example.com". */
  previewUrl: string;
}

/** The canonical `.env.preview` body. One placeholder per required value. */
export const PR_ENV_TEMPLATE = `# Auto-generated by agent-hub PR-env builder.
# DO NOT EDIT — regenerated on every pull_request.synchronize.
REPO_FULL_NAME=\${repoFullName}
PR_NUMBER=\${prNumber}
POOL_SLOT_ID=\${slotId}
HOST_PORT=\${hostPort}
DB_PATH=\${dbPath}
GITHUB_APP_ID=\${githubAppId}
GITHUB_INSTALLATION_ID=\${githubInstallationId}
GITHUB_PRIVATE_KEY=\${githubPrivateKey}
PREVIEW_URL=\${previewUrl}
`;

/**
 * Thrown when the template references a placeholder that wasn't supplied,
 * or when a supplied value is empty/blank for a required field. Message
 * lists every missing name so callers don't have to re-run to find the
 * next gap.
 */
export class EnvTemplateError extends Error {
  public readonly missing: string[];
  constructor(missing: string[]) {
    super(
      `PR-env template missing required value(s): ${missing.join(', ')}. ` +
        `Refusing to write a .env.preview with empty fields.`,
    );
    this.name = 'EnvTemplateError';
    this.missing = missing;
  }
}

/**
 * Render the template body with the supplied values. All placeholders
 * must be present and non-empty; otherwise throws `EnvTemplateError`.
 * Multiline values (notably the PEM private key) are escaped to `\n`
 * sequences since dotenv treats bare newlines as the end of the value.
 */
export function renderEnvFile(template: string, values: Record<string, string | number>): string {
  // Discover every placeholder the template references so we can
  // validate the caller supplied all of them.
  const referenced = new Set<string>();
  const placeholderRe = /\$\{([A-Za-z_][A-Za-z0-9_]*)\}/g;
  let m: RegExpExecArray | null;
  while ((m = placeholderRe.exec(template)) !== null) {
    referenced.add(m[1]);
  }

  const missing: string[] = [];
  for (const key of referenced) {
    const raw = values[key];
    if (raw === undefined || raw === null) {
      missing.push(key);
      continue;
    }
    const s = String(raw);
    // Empty string counts as missing — an env file with `FOO=` is almost
    // always an operator bug, and we'd rather fail the compose-up here.
    if (s.length === 0 || /^\s+$/.test(s)) missing.push(key);
  }
  if (missing.length > 0) throw new EnvTemplateError(missing);

  return template.replace(placeholderRe, (_match, name) => {
    const raw = values[name];
    return escapeEnvValue(String(raw));
  });
}

/**
 * Convenience wrapper that types the values and fills the standard
 * `PR_ENV_TEMPLATE`. Throws `EnvTemplateError` on any missing field.
 */
export function buildPrEnvFile(values: PrEnvTemplateValues): string {
  return renderEnvFile(PR_ENV_TEMPLATE, {
    repoFullName: values.repoFullName,
    prNumber: values.prNumber,
    slotId: values.slotId,
    hostPort: values.hostPort,
    dbPath: values.dbPath,
    githubAppId: values.githubAppId,
    githubInstallationId: values.githubInstallationId,
    githubPrivateKey: values.githubPrivateKey,
    previewUrl: values.previewUrl,
  });
}

/**
 * Escape a value so it's safe to drop after `KEY=` in a dotenv file.
 * - Strips carriage returns (CRLF → LF).
 * - Replaces LF with the two-character sequence `\n` so multi-line PEM
 *   keys stay on one line.
 * - Does NOT wrap in quotes — consumers (dotenv, docker compose
 *   --env-file) handle the `\n` unescape when parsing.
 */
function escapeEnvValue(value: string): string {
  return value.replace(/\r/g, '').replace(/\n/g, '\\n');
}
