/**
 * PR-env nginx server-block renderer (W2).
 *
 * Pure function — takes a PR number, host port, and cert paths, returns
 * the text of an nginx server block that terminates TLS on
 * `pr-<num>.<previewHost>` and proxies to `127.0.0.1:<port>`. The block is
 * modelled on the production `:443` block in `ops/nginx/agent-hub.conf`
 * but strips the WebSocket upgrade map + `/ws` sanitized logging: preview
 * envs run their own app stack (the container wraps its own server and
 * terminates its own WS inside), so the per-PR block just needs a single
 * `location /` that forwards everything with the Upgrade/Connection
 * headers threaded so WS *does* still work upstream.
 *
 * This file intentionally knows nothing about the filesystem or
 * `systemctl`. Callers (nginx-writer.ts) hand the string to fs.writeFile
 * and drive the reload. Keeping the renderer pure means tests can snapshot
 * the output without mocking child_process.
 */

export interface PreviewServerBlockInput {
  /** PR number — the subdomain becomes `pr-<prNumber>.<previewHost>`. */
  prNumber: number;
  /** Host port assigned by the PR-env port pool (allocated in pool_slots). */
  port: number;
  /**
   * Base hostname the wildcard cert covers, e.g. `preview.agenthub.dev`.
   * Must NOT include the `pr-<n>.` prefix — the renderer adds it.
   */
  previewHost: string;
  /** Absolute path to the fullchain cert (typically the wildcard). */
  certPath: string;
  /** Absolute path to the private key matching `certPath`. */
  keyPath: string;
}

/**
 * Render the HTTPS server block for a single PR preview env, plus an
 * accompanying :80 block that redirects to HTTPS (matching the parent
 * config's pattern of keeping ACME challenge on :80 but forcing everything
 * else to TLS).
 *
 * The returned string is the full file contents that should be dropped
 * into `/etc/nginx/sites-available/pr-<n>.preview.conf`.
 */
export function renderPreviewServerBlock(input: PreviewServerBlockInput): string {
  validateInput(input);
  const serverName = `pr-${input.prNumber}.${input.previewHost}`;
  const upstream = `http://127.0.0.1:${input.port}`;

  // NOTE: Do NOT emit HSTS here — the parent agent-hub.conf already emits
  // `includeSubDomains` from the apex, which covers every preview host.
  // Emitting HSTS twice is harmless but noisy in browser logs.
  //
  // WebSocket upgrade map: we declare a PR-scoped `$pr_<n>_connection_upgrade`
  // variable at the top of each rendered file. Why PR-scoped (not a plain
  // `$connection_upgrade`)? Nginx rejects redeclaration of an existing map
  // variable, so a plain name would collide with the parent agent-hub.conf
  // which already defines `$connection_upgrade` at the http { } level.
  // Using `$pr_<n>_` makes the file self-contained (nginx -t passes even
  // without the parent map present) while staying collision-free between
  // the parent conf and any sibling PR block.
  const upgradeVar = `pr_${input.prNumber}_connection_upgrade`;
  return `# ==============================================================================
# Auto-generated by agent-hub PR-env builder — PR #${input.prNumber}
# DO NOT EDIT — regenerated on every pull_request.synchronize event.
# Delete via \`agent-hub\` teardown when the PR closes.
#
# Self-contained: emits its own \`$${upgradeVar}\` map so \`nginx -t\` passes
# on hosts that don't pre-load the parent agent-hub.conf \`$connection_upgrade\`
# map (e.g. fresh installs). The PR-scoped variable name avoids collision
# with the parent map when both are loaded.
# ==============================================================================

# WebSocket upgrade map — scoped with a PR-unique variable name so it
# coexists with the parent agent-hub.conf $connection_upgrade without
# nginx complaining about duplicate map declarations.
map $http_upgrade $${upgradeVar} {
    default upgrade;
    ''      close;
}

server {
    listen 80;
    listen [::]:80;
    server_name ${serverName};

    # ACME HTTP-01 stays on :80 plaintext so the wildcard renewal path
    # can still fall back to HTTP-01 per host if DNS-01 breaks.
    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type "text/plain";
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${serverName};

    ssl_certificate     ${input.certPath};
    ssl_certificate_key ${input.keyPath};

    ssl_protocols        TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    ssl_session_timeout  1d;
    ssl_session_cache    shared:MozSSL:10m;
    ssl_session_tickets  off;
    ssl_stapling         on;
    ssl_stapling_verify  on;

    add_header X-Frame-Options         "DENY" always;
    add_header X-Content-Type-Options  "nosniff" always;
    add_header Referrer-Policy         "strict-origin-when-cross-origin" always;

    access_log /var/log/nginx/pr-${input.prNumber}-access.log;
    error_log  /var/log/nginx/pr-${input.prNumber}-error.log warn;

    client_max_body_size 100m;

    # Single catch-all location — the preview container handles routing,
    # WebSockets, static assets, and uploads internally.
    location / {
        proxy_pass ${upstream};
        proxy_http_version 1.1;

        # WebSocket upgrade passthrough. Uses the file-local map
        # ($${upgradeVar}) so this block is self-contained and doesn't
        # depend on the parent conf loading its own $connection_upgrade.
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        $${upgradeVar};

        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }
}
`;
}

/**
 * Filename (basename) for the sites-available conf file for a given PR.
 * Exported so the writer and teardown can agree on the path without
 * re-deriving it.
 */
export function previewConfFilename(prNumber: number): string {
  return `pr-${prNumber}.preview.conf`;
}

function validateInput(input: PreviewServerBlockInput): void {
  const missing: string[] = [];
  if (!Number.isInteger(input.prNumber) || input.prNumber <= 0) missing.push('prNumber');
  if (!Number.isInteger(input.port) || input.port <= 0 || input.port > 65535) missing.push('port');
  if (!input.previewHost || /\s/.test(input.previewHost)) missing.push('previewHost');
  if (!input.certPath || !input.certPath.startsWith('/')) missing.push('certPath');
  if (!input.keyPath || !input.keyPath.startsWith('/')) missing.push('keyPath');
  if (missing.length > 0) {
    throw new Error(
      `renderPreviewServerBlock: invalid input — ${missing.join(', ')}. ` +
        `All fields are required; paths must be absolute.`,
    );
  }
  // Disallow a previewHost that already starts with `pr-<n>.` — caller
  // must pass the *base* host only. Easy to get wrong from config.
  if (/^pr-\d+\./.test(input.previewHost)) {
    throw new Error(
      `renderPreviewServerBlock: previewHost must be the base wildcard host ` +
        `(e.g. "preview.agenthub.dev"), got "${input.previewHost}".`,
    );
  }
}
