/**
 * Zod schemas + OpenAPI registrations for the per-project AWS routes.
 *
 * Companion to `server/routes/project-aws.ts`. Loaded for its side
 * effects by `server/openapi/generate.ts` to populate the public spec
 * and to satisfy the `check:openapi-coverage` ratchet — the route file
 * has 4 `router.<verb>` handlers and the baseline starts new files at
 * `allowed_unregistered: 0`.
 */

import { z, registerPath, registerComponent } from '../openapi/registry.js';

// ─── Reusable building blocks ─────────────────────────────────────

const ProjectIdParam = z.object({
  projectId: z.string().openapi({ description: 'Project slug (e.g. `agent-hub`).' }),
});

const AwsRegion = z
  .string()
  .openapi({ description: 'AWS region code, e.g. `us-east-2`.', example: 'us-east-2' });

const ProjectAwsSsoProfile = registerComponent(
  'ProjectAwsSsoProfile',
  z
    .object({
      type: z.literal('sso').optional().openapi({
        description: 'Profile kind. Omitted legacy profiles are treated as SSO profiles.',
      }),
      sso_account_id: z
        .string()
        .openapi({ description: '12-digit AWS account id.', example: '123456789012' }),
      sso_start_url: z.string().openapi({
        description: 'IAM Identity Center start URL (`https://…`).',
        example: 'https://d-1234567890.awsapps.com/start/',
      }),
      sso_region: AwsRegion,
      sso_role_name: z.string().openapi({ description: 'IAM Identity Center role to assume.' }),
      region: AwsRegion,
      output: z
        .string()
        .optional()
        .openapi({ description: 'AWS CLI default output format; defaults to `json` on render.' }),
    })
    .openapi({
      description:
        "One AWS IAM Identity Center (SSO) profile stanza. Rendered into the per-spawn `AWS_CONFIG_FILE` as a `[profile <name>]` section. Not credentials — SSO tokens still live under the spawning user's `~/.aws/sso/cache`.",
    }),
);

const ProjectAwsStaticProfile = registerComponent(
  'ProjectAwsStaticProfile',
  z
    .object({
      type: z.literal('static'),
      aws_access_key_id: z.string().openapi({
        description: 'AWS access key id for this project-scoped profile.',
        example: 'AKIAIOSFODNN7EXAMPLE',
      }),
      aws_secret_access_key: z.string().openapi({
        description:
          'AWS secret access key. Returned by the current admin API because project config is editable by Owners; callers must treat it as secret material.',
      }),
      aws_session_token: z
        .string()
        .optional()
        .openapi({ description: 'Optional temporary session token.' }),
      region: AwsRegion,
      output: z
        .string()
        .optional()
        .openapi({ description: 'AWS CLI default output format; defaults to `json` on render.' }),
    })
    .openapi({
      description:
        'One static-credential profile. Rendered into the project-scoped `AWS_SHARED_CREDENTIALS_FILE` as a `[name]` section and paired with a `[profile name]` config section for region/output.',
    }),
);

const ProjectAwsRoleProfile = registerComponent(
  'ProjectAwsRoleProfile',
  z
    .object({
      type: z.literal('role'),
      role_arn: z.string().openapi({
        description: 'IAM role to assume.',
        example: 'arn:aws:iam::123456789012:role/AgentHubMonitoring',
      }),
      external_id: z.string().optional().openapi({
        description:
          "External ID presented on AssumeRole and matched by the role's trust policy. Generated by the Hub and identical to `externalId` on the profiles response; any value sent here is discarded, because an operator-chosen external ID would not defend against the confused-deputy problem it exists for.",
      }),
      source_profile: z.string().optional().openapi({
        description:
          'Another profile in this project to chain from. Mutually exclusive with `credential_source`.',
      }),
      credential_source: z
        .enum(['Environment', 'Ec2InstanceMetadata', 'EcsContainer'])
        .optional()
        .openapi({
          description:
            "Where the base credentials come from when not chained. Omit to follow the Hub's detected runtime — see `ambientCredentialSource` on the profiles response.",
        }),
      role_session_name: z
        .string()
        .optional()
        .openapi({ description: 'Session name recorded in CloudTrail for the assumed role.' }),
      region: AwsRegion,
      output: z
        .string()
        .optional()
        .openapi({ description: 'AWS CLI default output format; defaults to `json` on render.' }),
    })
    .openapi({
      description:
        'One assume-role profile. Rendered into the project-scoped `AWS_CONFIG_FILE` as a `[profile <name>]` section with `role_arn` plus either `source_profile` or `credential_source`. Holds no secret material and needs no interactive login, so it is the profile kind unattended collection can use.',
    }),
);

const ProjectAwsProfile = registerComponent(
  'ProjectAwsProfile',
  z.union([ProjectAwsSsoProfile, ProjectAwsStaticProfile, ProjectAwsRoleProfile]).openapi({
    description:
      'An AWS profile stanza: IAM Identity Center (SSO), static credentials, or an assumed role.',
  }),
);

const ProjectAwsProfilesMap = registerComponent(
  'ProjectAwsProfilesMap',
  z.record(z.string(), ProjectAwsProfile).openapi({
    description: 'Map of profile name → profile stanza.',
  }),
);

const ProfilesEnvelope = registerComponent(
  'ProjectAwsProfilesResponse',
  z
    .object({
      profiles: ProjectAwsProfilesMap,
      externalId: z.string().openapi({
        description:
          "External ID this Hub presents when assuming any of the project's role profiles, and the value the customer puts in their role trust policy's `sts:ExternalId` condition. Hub-generated, unique per project, and read-only: AWS's confused-deputy guidance requires the assuming party to generate it, so a value the operator could choose would defeat its purpose. Minted on first read of this endpoint.",
        example: 'agent-hub-8f14e45f-ceea-467a-9c1e-6b1e5f8a0d2c',
      }),
      defaultProfile: z.string().nullable().openapi({
        description:
          'Profile the operator explicitly designated as the project default, or null when none is designated.',
      }),
      effectiveDefaultProfile: z.string().nullable().openapi({
        description:
          'Profile exported as `AWS_PROFILE` to spawns and the session Terminal: the designation when set, else the sole configured profile, else null. Without it, un-flagged `aws` commands fall back to a `[default]` section the project-scoped config file never has.',
      }),
      monitoringProfile: z.string().nullable().openapi({
        description:
          'Profile the operator designated for unattended background work (metric collection, alert evaluation), or null when none is designated. Never an SSO profile.',
      }),
      effectiveMonitoringProfile: z.string().nullable().openapi({
        description:
          'Profile background collection actually runs as: the designation when it still names a live non-SSO profile, else null. There is no sole-profile fallback — null means the Infrastructure module shows its "designate a monitoring profile" empty state.',
      }),
      ambientCredentialSource: z
        .enum(['Environment', 'Ec2InstanceMetadata', 'EcsContainer'])
        .openapi({
          description:
            'The `credential_source` this Hub renders for role profiles that name no origin, detected from the server runtime (container credential endpoint → `EcsContainer`, ambient key env vars → `Environment`, else `Ec2InstanceMetadata`) and overridable with `AGENT_HUB_AWS_CREDENTIAL_SOURCE`.',
        }),
    })
    .openapi({
      description: 'Current AWS profiles configured on the project.',
    }),
);

const PutProfilesBody = registerComponent(
  'ProjectAwsProfilesRequest',
  z
    .object({
      profiles: z.union([ProjectAwsProfilesMap, z.array(z.unknown())]).openapi({
        description:
          'Replacement set of profiles. Accepts either a `{ name: stanza }` map or an array of `{ name, ...stanza }` objects. Pass `{}` to clear all profiles.',
      }),
      defaultProfile: z.string().nullable().optional().openapi({
        description:
          'Profile to export as `AWS_PROFILE` for spawns and the session Terminal, so un-flagged `aws` commands resolve. Must name one of the profiles in this same request; pass null or omit to clear the designation.',
      }),
      monitoringProfile: z.string().nullable().optional().openapi({
        description:
          'Profile unattended background work runs as. Must name a `static` or `role` profile in this same request — an SSO profile is rejected with 400 because its token cache is HOME-keyed and expires with nobody around to re-run `aws sso login`. Pass null or omit to clear the designation.',
      }),
    })
    .openapi({ description: 'Body for PUT /aws-profiles.' }),
);

const ErrorEnvelope = registerComponent(
  'ProjectAwsErrorResponse',
  z
    .object({
      error: z.string(),
    })
    .openapi({ description: 'Error envelope for project-aws routes.' }),
);

const SsoStatusResponse = registerComponent(
  'ProjectAwsSsoStatusResponse',
  z
    .union([
      z.object({
        profile: z.string(),
        loggedIn: z.literal(true),
        credentialType: z.literal('sso').optional(),
        account: z.string().optional(),
        arn: z.string().optional(),
        userId: z.string().optional(),
        homeSource: z.enum(['caller', 'host', 'per-user']).openapi({
          description:
            "Which HOME's SSO token cache produced this identity: 'caller' (the requesting user's per-user HOME), 'host' (the shared break-glass/operator HOME), or 'per-user' (the caller's per-user HOME for a not-logged-in result).",
        }),
      }),
      z.object({
        profile: z.string(),
        loggedIn: z.literal(false),
        credentialType: z.literal('sso').optional(),
        error: z.string().optional(),
        needsLogin: z.boolean().optional(),
        homeSource: z.enum(['caller', 'host', 'per-user']).openapi({
          description:
            "Which HOME the caller should log into to authenticate this profile: 'per-user' (the requesting user's own HOME) or 'host' (the shared break-glass/operator HOME). Run POST /aws-sso/login under that HOME. (Not the last-probed HOME — both caller and host caches were checked and neither held a valid token.)",
        }),
      }),
      z.object({
        profile: z.string(),
        loggedIn: z.literal(true),
        credentialType: z.enum(['static', 'role']),
        account: z.string().optional(),
        arn: z.string().optional(),
        userId: z.string().optional(),
      }),
      z.object({
        profile: z.string(),
        loggedIn: z.literal(false),
        credentialType: z.enum(['static', 'role']),
        error: z.string().optional(),
        needsLogin: z.literal(false).optional(),
      }),
    ])
    .openapi({
      description:
        '`aws sts get-caller-identity` result for the named profile. SSO profiles probe the caller HOME first, then the shared host HOME as a fallback (never other users’ per-user HOMEs). Static profiles use the project-scoped credentials file and role profiles assume `role_arn` from the Hub’s ambient credentials; neither requires SSO login.',
    }),
);

const SsoLoginRequest = registerComponent(
  'ProjectAwsSsoLoginRequest',
  z
    .object({
      profile: z.string().openapi({ description: 'Configured profile name to log in.' }),
    })
    .openapi({ description: 'Body for POST /aws-sso/login.' }),
);

const SsoLoginResponse = registerComponent(
  'ProjectAwsSsoLoginResponse',
  z
    .union([
      z.object({
        ok: z.literal(true),
        loginId: z.string().openapi({
          description: 'Server-local id for this login attempt — useful for log correlation.',
        }),
        profile: z.string(),
        loginUrl: z.string().optional().openapi({
          description:
            'IAM Identity Center device-authorization URL the user must open in a browser. Present on the standard happy path where the URL surfaces within ~30 seconds.',
        }),
        completed: z.boolean().optional().openapi({
          description:
            'True when `aws sso login --no-browser` finished entirely server-side (rare — usually the user completes the device flow in a browser before the CLI exits).',
        }),
        output: z.string().optional().openapi({
          description: 'Tail of the CLI stdout/stderr (capped) for diagnostic purposes.',
        }),
      }),
      z.object({
        ok: z.literal(false),
        loginId: z.string(),
        profile: z.string(),
        error: z.string(),
        output: z.string().optional(),
      }),
    ])
    .openapi({
      description:
        'Outcome of the browser-less `aws sso login` spawn. Only one login proc runs per server at a time; if a second request arrives while a previous one is still running the previous proc is killed and a new one is spawned.',
    }),
);

// ─── Path registrations ───────────────────────────────────────────

const jsonContent = <T extends z.ZodTypeAny>(schema: T) => ({
  'application/json': { schema },
});

// GET /api/projects/{projectId}/aws-profiles
registerPath({
  method: 'get',
  path: '/api/projects/{projectId}/aws-profiles',
  tags: ['Projects'],
  summary: 'List AWS profiles configured on a project',
  description:
    "Returns the project's AWS profile map. SSO token caches are never returned. Static profile access keys are part of this owner-managed project config and must be treated as secret material.",
  request: { params: ProjectIdParam },
  responses: {
    200: {
      description: 'Profile map (may be empty).',
      content: jsonContent(ProfilesEnvelope),
    },
    404: {
      description: 'Project not found, or the caller cannot see it.',
      content: jsonContent(ErrorEnvelope),
    },
  },
});

// PUT /api/projects/{projectId}/aws-profiles
registerPath({
  method: 'put',
  path: '/api/projects/{projectId}/aws-profiles',
  tags: ['Projects'],
  summary: 'Replace the AWS profiles configured on a project',
  description:
    "Wholesale replace the project's AWS profile map. Pass an empty map to clear all profiles. After a successful save the server regenerates the on-disk `AWS_CONFIG_FILE` and `AWS_SHARED_CREDENTIALS_FILE` templates that future spawns reference.",
  request: {
    params: ProjectIdParam,
    body: { content: jsonContent(PutProfilesBody) },
  },
  responses: {
    200: {
      description: 'Profiles saved. Returns the normalized map.',
      content: jsonContent(ProfilesEnvelope),
    },
    400: {
      description:
        'Validation failed — bad profile name, invalid account id / region / URL, duplicate keys, or a `monitoringProfile` naming an SSO profile.',
      content: jsonContent(ErrorEnvelope),
    },
    404: {
      description: 'Project not found, or the caller cannot see it.',
      content: jsonContent(ErrorEnvelope),
    },
  },
});

// GET /api/projects/{projectId}/aws-sso/status
registerPath({
  method: 'get',
  path: '/api/projects/{projectId}/aws-sso/status',
  tags: ['Projects'],
  summary: 'Check whether an AWS profile can authenticate',
  description:
    "Runs `aws sts get-caller-identity --profile <name>` against the project's rendered AWS config and credentials files. SSO profiles report whether cached SSO tokens can authenticate. Static profiles report whether the stored project credentials can authenticate.",
  request: {
    params: ProjectIdParam,
    query: z.object({
      profile: z.string().openapi({ description: 'Configured profile name.' }),
    }),
  },
  responses: {
    200: {
      description:
        'Identity check ran. Inspect `loggedIn` to know whether the token is valid — a 200 is also returned for the "not logged in" case so callers can branch on the body without try/catch.',
      content: jsonContent(SsoStatusResponse),
    },
    400: {
      description: 'Project has no AWS profiles configured, or the profile name is unknown.',
      content: jsonContent(ErrorEnvelope),
    },
    404: {
      description: 'Project not found, or the caller cannot see it.',
      content: jsonContent(ErrorEnvelope),
    },
  },
});

// POST /api/projects/{projectId}/aws-sso/login
registerPath({
  method: 'post',
  path: '/api/projects/{projectId}/aws-sso/login',
  tags: ['Projects'],
  summary: 'Start a browser-less AWS SSO device-authorization flow',
  description:
    'Spawns `aws sso login --profile <name> --no-browser` server-side, watches its output for the IAM Identity Center device URL, and returns the URL to the caller. The user then opens that URL in their own browser to complete the device flow; once they do, the cached SSO token at `~/.aws/sso/cache` becomes valid and subsequent `GET /aws-sso/status` calls report `loggedIn: true`.\n\nOnly one login proc runs per server at a time: a second request kills the previous proc before spawning a new one. The 30-second URL-extraction timeout also kills the proc so no orphaned `aws` processes accumulate.',
  request: {
    params: ProjectIdParam,
    body: { content: jsonContent(SsoLoginRequest) },
  },
  responses: {
    200: {
      description:
        'Login proc spawned. On the happy path the response carries `loginUrl`; on rare immediate completion it carries `completed: true`.',
      content: jsonContent(SsoLoginResponse),
    },
    400: {
      description:
        'Project has no AWS profiles configured, the profile name is unknown, or the profile is not an SSO profile (static credentials or an assumed role).',
      content: jsonContent(ErrorEnvelope),
    },
    404: {
      description: 'Project not found, or the caller cannot see it.',
      content: jsonContent(ErrorEnvelope),
    },
    500: {
      description:
        'Login proc failed — exited non-zero, errored on spawn, or timed out without surfacing a device URL.',
      content: jsonContent(SsoLoginResponse),
    },
  },
});
