/**
 * push-and-create-pr.ts — Finalize Code Changes, §8 push step.
 *
 * Wires the orchestrator's injected {@link PushAndCreatePrFn} seam to a real
 * `git push --force-with-lease -u origin <branch>` + `gh pr create` pair.
 *
 * v0 contract (intentionally minimal):
 *   - Auth via {@link resolveOrgOwnerGithubToken}, shaped with
 *     {@link autoGitChildEnv} (token scrub + helper isolation, see auto-git.ts).
 *   - Body is a single-line marker — full templating (rich PR body, footer,
 *     etc.) is a follow-up. The orchestrator's provenance helper
 *     (`./provenance.ts`) handles body-marker injection downstream.
 *   - Throws on error — the orchestrator catches and maps to
 *     `infra_error / github_push_5xx` (see `terminate()` in `orchestrator.ts`).
 */
import { execFile } from 'child_process';
import { promisify } from 'util';
import type { AppConfig } from '../types.js';
import { autoGitChildEnv, resolveOrgOwnerGithubToken } from '../auto-git.js';
import type {
  PushAndCreatePrArgs,
  PushAndCreatePrFn,
  PushAndCreatePrResult,
} from './orchestrator.js';

const execFileAsync = promisify(execFile);

/**
 * Run a command, rethrowing with stderr/stdout folded into the message.
 *
 * `execFileAsync`'s rejection `.message` is typically just `Command failed:
 * <cmd>` — the actual git / gh diagnostic lands on `err.stderr`, which the
 * Finalize push path otherwise discards. Folding it in here is what makes the
 * `[finalize-push] github_push_5xx ...` server log line actionable.
 */
async function execGit(
  file: string,
  argv: string[],
  opts: Parameters<typeof execFileAsync>[2],
): Promise<{ stdout: string; stderr: string }> {
  try {
    const result = await execFileAsync(file, argv, opts);
    return { stdout: String(result.stdout), stderr: String(result.stderr) };
  } catch (err) {
    const e = err as { message?: string; stderr?: unknown; stdout?: unknown };
    const stderr = e.stderr ? String(e.stderr).trim() : '';
    const stdout = e.stdout ? String(e.stdout).trim() : '';
    const detail = stderr || stdout;
    const base = `${file} ${argv[0] ?? ''} failed: ${e.message ?? 'unknown error'}`;
    throw new Error(detail ? `${base}\n${detail}` : base);
  }
}

/** Per-call timeout for `git push` / `gh pr create`. Generous — large pushes are slow. */
const PUSH_TIMEOUT_MS = 5 * 60 * 1000;

/** Cap stdout/stderr at 10 MiB to match auto-git.ts's STREAM_OUTPUT_MAX_BYTES. */
const MAX_BUFFER = 10 * 1024 * 1024;

/**
 * Extract the PR URL from `gh pr create` stdout. `gh` emits the URL on its
 * own line (typically last); we take the first https:// line as the
 * authoritative URL.
 */
function parsePrUrl(stdout: string): string | null {
  for (const line of stdout.split('\n')) {
    const trimmed = line.trim();
    if (trimmed.startsWith('https://github.com/') && trimmed.includes('/pull/')) {
      return trimmed;
    }
  }
  return null;
}

/**
 * Build a real {@link PushAndCreatePrFn} bound to the supplied `AppConfig`.
 * The orchestrator calls the returned function once per finalize run.
 */
export function createPushAndCreatePr(deps: {
  config: Pick<AppConfig, 'personalOAuth' | 'githubApp'>;
}): PushAndCreatePrFn {
  return async function pushAndCreatePr(args: PushAndCreatePrArgs): Promise<PushAndCreatePrResult> {
    const token = await resolveOrgOwnerGithubToken(deps.config, args.project.githubRepo ?? null);
    const env = autoGitChildEnv(token);

    // git push --force-with-lease -u origin <branch>
    await execGit('git', ['push', '--force-with-lease', '-u', 'origin', args.branch], {
      cwd: args.worktreePath,
      env,
      timeout: PUSH_TIMEOUT_MS,
      maxBuffer: MAX_BUFFER,
    });

    // gh pr create --base <baseBranch> --head <branch> --title <card.title> --body <body>
    // v0: single-line body marker. Templating is a follow-up.
    const body = 'Auto-generated by Finalize Code Changes.';
    const { stdout } = await execGit(
      'gh',
      [
        'pr',
        'create',
        '--base',
        args.baseBranch,
        '--head',
        args.branch,
        '--title',
        args.card.title,
        '--body',
        body,
      ],
      { cwd: args.worktreePath, env, timeout: PUSH_TIMEOUT_MS, maxBuffer: MAX_BUFFER },
    );

    const prUrl = parsePrUrl(stdout);
    if (!prUrl) {
      throw new Error(`gh pr create returned no parseable PR URL; stdout: ${stdout.slice(0, 500)}`);
    }
    return { prUrl };
  };
}

// Exported for tests.
export const __test = { parsePrUrl };
