import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from 'fs';
import path from 'path';
import { spawn, type ChildProcess } from 'child_process';
import { trackChild, killProcessGroup } from './process-groups.js';
import { disableNativeSkillToolArgs } from './claude-cli-args.js';

export function localDateStr(d = new Date()): string {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

function today(): string {
  return localDateStr();
}

function yesterday(): string {
  const d = new Date();
  d.setDate(d.getDate() - 1);
  return localDateStr(d);
}

export function getMemoryContext(workspace: string | undefined): string {
  if (!workspace) return '';

  const parts: string[] = [];

  const memoryPath = path.join(workspace, 'MEMORY.md');
  if (existsSync(memoryPath)) {
    try {
      let memory = readFileSync(memoryPath, 'utf-8');
      if (memory.length > 2000) {
        memory = '...(truncated)\n' + memory.slice(-2000);
      }
      if (memory.trim()) {
        parts.push(`## MEMORY.md (Long-term)\n${memory}`);
      }
    } catch {
      /* skip */
    }
  }

  const todayPath = path.join(workspace, 'memory', `${today()}.md`);
  if (existsSync(todayPath)) {
    try {
      let content = readFileSync(todayPath, 'utf-8');
      if (content.length > 3000) {
        content = '...(truncated)\n' + content.slice(-3000);
      }
      if (content.trim()) {
        parts.push(`## Today's Notes (${today()})\n${content}`);
      }
    } catch {
      /* skip */
    }
  }

  const yesterdayPath = path.join(workspace, 'memory', `${yesterday()}.md`);
  if (existsSync(yesterdayPath)) {
    try {
      let content = readFileSync(yesterdayPath, 'utf-8');
      if (content.length > 1500) {
        content = '...(truncated)\n' + content.slice(-1500);
      }
      if (content.trim()) {
        parts.push(`## Yesterday's Notes (${yesterday()})\n${content}`);
      }
    } catch {
      /* skip */
    }
  }

  return parts.length > 0 ? parts.join('\n\n') : '';
}

export function appendDailyNote(workspace: string | undefined, entry: string): void {
  if (!workspace) return;

  const memoryDir = path.join(workspace, 'memory');
  mkdirSync(memoryDir, { recursive: true });

  const filePath = path.join(memoryDir, `${today()}.md`);
  const now = new Date();
  const time = `${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`;
  const formatted = `## ${time}\n${entry}\n\n`;

  try {
    let existing = '';
    if (existsSync(filePath)) {
      existing = readFileSync(filePath, 'utf-8');
    }
    writeFileSync(filePath, existing + formatted, 'utf-8');
  } catch (err) {
    console.error('Failed to append daily note:', (err as Error).message);
  }
}

export function updateMemory(workspace: string | undefined, content: string): void {
  if (!workspace) return;

  const memoryPath = path.join(workspace, 'MEMORY.md');
  try {
    writeFileSync(memoryPath, content, 'utf-8');
  } catch (err) {
    console.error('Failed to update MEMORY.md:', (err as Error).message);
  }
}

interface DailyNote {
  date: string;
  content: string;
}

interface MemoryData {
  memory: string;
  dailyNotes: DailyNote[];
}

export function getMemoryData(workspace: string | undefined): MemoryData {
  if (!workspace) return { memory: '', dailyNotes: [] };

  let memory = '';
  const memoryPath = path.join(workspace, 'MEMORY.md');
  if (existsSync(memoryPath)) {
    try {
      memory = readFileSync(memoryPath, 'utf-8');
    } catch {
      /* skip */
    }
  }

  const dailyNotes: DailyNote[] = [];
  const memoryDir = path.join(workspace, 'memory');
  if (existsSync(memoryDir)) {
    try {
      const files = readdirSync(memoryDir)
        .filter((f) => f.endsWith('.md'))
        .sort()
        .reverse()
        .slice(0, 14);
      for (const file of files) {
        try {
          const content = readFileSync(path.join(memoryDir, file), 'utf-8');
          dailyNotes.push({ date: file.replace('.md', ''), content });
        } catch {
          /* skip */
        }
      }
    } catch {
      /* skip */
    }
  }

  return { memory, dailyNotes };
}

// ─── Memory Reconciliation ─────────────────────────────────────────

let reconcileLock: Promise<unknown> = Promise.resolve();

function withReconcileLock<T>(fn: () => Promise<T>): Promise<T> {
  const next = reconcileLock.then(fn, fn);
  reconcileLock = next.catch(() => {});
  return next;
}

interface ClaudeRunOptions {
  claudeBin: string;
  spawnEnv: NodeJS.ProcessEnv;
  cwd?: string;
  timeoutMs?: number;
}

/**
 * Spawn Claude in --print mode with a prompt and return the result.
 *
 * Trust assumptions for --permission-mode bypassPermissions:
 * - MEMORY.md content is written by our own reconciliation logic or the project owner.
 * - Session summaries are generated by our own summarizeTranscript function.
 * - Wiki pages are authored by authenticated project collaborators.
 * If any of these trust boundaries change (e.g. user-submitted wiki content),
 * this should be revisited — consider using a restricted permission mode
 * or sanitizing inputs before passing them as prompts.
 */
function runClaudeForMemory(
  prompt: string,
  systemPrompt: string | undefined,
  { claudeBin, spawnEnv, cwd, timeoutMs = 3 * 60 * 1000 }: ClaudeRunOptions,
): Promise<string> {
  return new Promise((resolve, reject) => {
    const args = ['--print', '--permission-mode', 'bypassPermissions'];
    if (systemPrompt) args.push('--system-prompt', systemPrompt);
    // see claude-cli-args.ts
    args.push(...disableNativeSkillToolArgs());
    // `--` terminates option parsing so the variadic `--disallowed-tools <tools...>`
    // doesn't swallow the trailing positional prompt (Claude CLI 2.x).
    args.push('--', prompt);

    let output = '';
    let errorOutput = '';

    const proc: ChildProcess = spawn(claudeBin, args, {
      cwd: cwd || process.env.HOME,
      env: spawnEnv,
      stdio: ['ignore', 'pipe', 'pipe'],
      detached: true,
    });
    trackChild(proc);

    const timer = setTimeout(() => {
      killProcessGroup(proc, 'SIGTERM');
      reject(new Error('Memory reconciliation timed out'));
    }, timeoutMs);

    proc.stdout!.on('data', (chunk: Buffer) => {
      output += chunk.toString();
    });
    proc.stderr!.on('data', (chunk: Buffer) => {
      errorOutput += chunk.toString();
    });

    proc.on('close', (code: number | null) => {
      clearTimeout(timer);
      if (code === 0) {
        resolve(output.trim());
      } else {
        reject(new Error(errorOutput || `Exited with code ${code}`));
      }
    });

    proc.on('error', (err: Error) => {
      clearTimeout(timer);
      reject(err);
    });
  });
}

export function reconcileMemoryAfterSession(
  workspace: string | undefined,
  sessionSummary: string,
  opts: ClaudeRunOptions,
): Promise<void> {
  if (!workspace || !sessionSummary) return Promise.resolve();

  return withReconcileLock(async () => {
    const memoryPath = path.join(workspace, 'MEMORY.md');
    if (!existsSync(memoryPath)) return;

    let currentMemory: string;
    try {
      currentMemory = readFileSync(memoryPath, 'utf-8');
    } catch {
      return;
    }

    if (!currentMemory.trim()) return;

    const systemPrompt = [
      'You are a memory file maintainer. You will receive the current MEMORY.md file and a session summary.',
      'Your job is to check whether the session summary reveals any FACTS that contradict or are missing from MEMORY.md.',
      '',
      'Rules:',
      '- Only update FACTUAL sections (e.g. "Key Decisions", "Project Structure", "Important Ports").',
      '- Do NOT touch daily notes, session logs, or timestamps.',
      '- Do NOT add session-specific details — those belong in daily notes, not long-term memory.',
      '- If nothing needs changing, respond with exactly: NO_CHANGES_NEEDED',
      '- If changes are needed, respond with the COMPLETE updated MEMORY.md content.',
      '- Preserve the existing structure and formatting exactly.',
      '- Be conservative — only change lines where you are confident the current info is wrong or outdated.',
    ].join('\n');

    const prompt = [
      '## Current MEMORY.md',
      '```',
      currentMemory,
      '```',
      '',
      '## Session Summary (just completed)',
      '```',
      sessionSummary,
      '```',
      '',
      'Check if MEMORY.md needs factual corrections based on this session. Follow your instructions exactly.',
    ].join('\n');

    try {
      const result = await runClaudeForMemory(prompt, systemPrompt, opts);
      if (!result || result.includes('NO_CHANGES_NEEDED')) {
        console.log('[Memory Reconciliation] No changes needed after session.');
        return;
      }

      const MAX_MEMORY_SIZE = 100_000;
      const maxAllowed = Math.max(currentMemory.length * 3, 1000);
      if (result.length < 50 || result.length > maxAllowed || result.length > MAX_MEMORY_SIZE) {
        console.warn('[Memory Reconciliation] Skipping — result looks malformed.');
        return;
      }

      writeFileSync(memoryPath + '.bak', currentMemory, 'utf-8');

      updateMemory(workspace, result);
      appendDailyNote(
        workspace,
        '**Memory Reconciliation** — MEMORY.md updated based on session findings.',
      );
      console.log('[Memory Reconciliation] MEMORY.md updated after session.');
    } catch (err) {
      console.error('[Memory Reconciliation] Failed:', (err as Error).message);
    }
  });
}

interface WikiPageInput {
  title: string;
  content: string;
  category: string;
}

export function reconcileMemoryFromWiki(
  workspace: string | undefined,
  wikiPages: WikiPageInput[] | undefined,
  opts: ClaudeRunOptions,
): Promise<void> {
  if (!workspace || !wikiPages?.length) return Promise.resolve();

  return withReconcileLock(async () => {
    const memoryPath = path.join(workspace, 'MEMORY.md');
    if (!existsSync(memoryPath)) return;

    let currentMemory: string;
    try {
      currentMemory = readFileSync(memoryPath, 'utf-8');
    } catch {
      return;
    }

    if (!currentMemory.trim()) return;

    const wikiDigest = wikiPages
      .map((p) => {
        const truncated =
          p.content.length > 800 ? p.content.substring(0, 800) + '...(truncated)' : p.content;
        return `### ${p.title} (${p.category})\n${truncated}`;
      })
      .join('\n\n');

    const cappedDigest =
      wikiDigest.length > 15000
        ? wikiDigest.substring(0, 15000) + '\n\n...(remaining pages truncated)'
        : wikiDigest;

    const systemPrompt = [
      'You are a memory file maintainer. You will receive the current MEMORY.md and a digest of all wiki pages.',
      'The wiki is the authoritative source of truth about this project.',
      '',
      'Your job:',
      '1. Compare MEMORY.md against the wiki content.',
      '2. Fix any facts in MEMORY.md that the wiki shows are wrong or outdated.',
      '3. Add any important architectural facts from the wiki that are missing from MEMORY.md.',
      '',
      'Rules:',
      '- Only update FACTUAL sections (e.g. "Key Decisions", "Project Structure", "Important Ports").',
      '- Do NOT touch daily notes, session logs, timestamps, or "Unresolved" items.',
      '- Do NOT copy wiki content verbatim — MEMORY.md should be a concise summary.',
      '- Preserve the existing MEMORY.md structure and formatting.',
      '- If nothing needs changing, respond with exactly: NO_CHANGES_NEEDED',
      '- If changes are needed, respond with the COMPLETE updated MEMORY.md content.',
      '- Be conservative — only change what you are confident is wrong.',
    ].join('\n');

    const prompt = [
      '## Current MEMORY.md',
      '```',
      currentMemory,
      '```',
      '',
      '## Wiki Pages (source of truth)',
      cappedDigest,
      '',
      'Reconcile MEMORY.md against the wiki. Follow your instructions exactly.',
    ].join('\n');

    try {
      const result = await runClaudeForMemory(prompt, systemPrompt, {
        ...opts,
        timeoutMs: 5 * 60 * 1000,
      });
      if (!result || result.includes('NO_CHANGES_NEEDED')) {
        console.log('[Wiki→Memory Sync] No changes needed.');
        return;
      }

      const MAX_MEMORY_SIZE = 100_000;
      const maxAllowed = Math.max(currentMemory.length * 3, 1000);
      if (result.length < 50 || result.length > maxAllowed || result.length > MAX_MEMORY_SIZE) {
        console.warn('[Wiki→Memory Sync] Skipping — result looks malformed.');
        return;
      }

      writeFileSync(memoryPath + '.bak', currentMemory, 'utf-8');

      updateMemory(workspace, result);
      appendDailyNote(
        workspace,
        '**Wiki→Memory Sync** — MEMORY.md reconciled against project wiki.',
      );
      console.log('[Wiki→Memory Sync] MEMORY.md updated from wiki.');
    } catch (err) {
      console.error('[Wiki→Memory Sync] Failed:', (err as Error).message);
    }
  });
}
