import { parseLogLine } from './release-notes-parse.js';

export type ReleaseNoteItem = {
  text: string;
  hash: string | null;
};

export type ReleaseNoteSection = {
  title: string;
  items: ReleaseNoteItem[];
};

export type UserFacingRelease = {
  version: string;
  tag: string;
  publishedAt: string | null;
  url: string | null;
  /** One-line preview for the version list */
  summary: string;
  sections: ReleaseNoteSection[];
};

const DEV_SECTION_TITLES = new Set([
  'Documentation',
  'Tests',
  'Build',
  'CI',
  'Chores',
  'Refactors',
]);

const SECTION_TO_USER: Record<string, string> = {
  Features: "What's new",
  'Bug Fixes': 'Bug fixes',
  Performance: 'Faster & smoother',
  Refactors: 'Improvements',
  Other: 'More changes',
};

const TYPE_VERB: Record<string, string> = {
  feat: 'Added',
  fix: 'Fixed',
  perf: 'Improved',
  refactor: 'Improved',
  docs: 'Updated docs for',
  test: 'Added tests for',
  build: 'Updated build for',
  ci: 'Updated CI for',
  chore: 'Maintained',
};

/**
 * Turn a Conventional Commit subject into plain language for the release page.
 */
export function humanizeCommitSubject(subject: string): string {
  const cc = subject.match(/^([a-z]+)(\(([^)]+)\))?(!)?:\s*(.+)$/i);
  if (!cc) {
    const t = subject.trim();
    return t.length > 0 ? t.charAt(0).toUpperCase() + t.slice(1) : subject;
  }
  const type = cc[1].toLowerCase();
  const scope = cc[3]?.trim();
  const breaking = !!cc[4];
  let desc = cc[5].trim();
  const stripDup = {
    feat: /^add\s+/i,
    fix: /^fix\s+/i,
    perf: /^improve\s+/i,
    refactor: /^refactor\s+/i,
  }[type];
  if (stripDup) desc = desc.replace(stripDup, '');
  if (desc.length > 0) {
    desc = desc.charAt(0).toUpperCase() + desc.slice(1);
  }
  const verb = TYPE_VERB[type] ?? null;
  if (!verb) return desc || subject;
  const scopeBit = scope ? ` (${scope})` : '';
  if (breaking) {
    return `Breaking: ${desc}${scopeBit}`.replace(/\s+/g, ' ').trim();
  }
  return `${verb} ${desc}${scopeBit}`.replace(/\s+/g, ' ').trim();
}

/** Parse bullets from GitHub release notes generated by format-release-notes.ts */
export function parseReleaseMarkdownBody(
  body: string,
): Array<{ section: string; subject: string; hash: string | null }> {
  const lines = body.split('\n');
  const out: Array<{ section: string; subject: string; hash: string | null }> = [];
  let section = 'Other';

  for (const raw of lines) {
    const line = raw.trim();
    if (line.startsWith('### ')) {
      section = line.slice(4).trim();
      continue;
    }
    if (!line.startsWith('- ')) continue;
    const parsed = parseLogLine(line);
    if (parsed) {
      out.push({ section, subject: parsed.subject, hash: parsed.hash });
      continue;
    }
    const loose = line.match(/^-\s+(.+?)(?:\s+\(`?([0-9a-f]{6,40})`?\))?\s*$/i);
    if (loose) {
      out.push({
        section,
        subject: loose[1].trim(),
        hash: loose[2] ?? null,
      });
    }
  }
  return out;
}

export function buildUserFacingSections(
  rows: Array<{ section: string; subject: string; hash: string | null }>,
  opts?: { includeDevSections?: boolean },
): ReleaseNoteSection[] {
  const includeDev = opts?.includeDevSections ?? false;
  const buckets = new Map<string, ReleaseNoteItem[]>();

  for (const row of rows) {
    if (!includeDev && DEV_SECTION_TITLES.has(row.section)) continue;
    const userTitle = SECTION_TO_USER[row.section] ?? SECTION_TO_USER.Other;
    if (!buckets.has(userTitle)) buckets.set(userTitle, []);
    buckets.get(userTitle)!.push({
      text: humanizeCommitSubject(row.subject),
      hash: row.hash,
    });
  }

  const order = ["What's new", 'Bug fixes', 'Faster & smoother', 'Improvements', 'More changes'];
  const sections: ReleaseNoteSection[] = [];
  for (const title of order) {
    const items = buckets.get(title);
    if (items && items.length > 0) {
      sections.push({ title, items });
    }
  }
  return sections;
}

export function summarizeRelease(sections: ReleaseNoteSection[]): string {
  const primary = sections.find((s) => s.title === "What's new") ?? sections[0];
  if (!primary || primary.items.length === 0) {
    return 'Updates and improvements in this release.';
  }
  const first = primary.items[0].text;
  if (primary.items.length === 1) return first;
  return `${first}, and more.`;
}

export function tagToVersion(tag: string): string {
  return tag.startsWith('v') ? tag.slice(1) : tag;
}

export function versionToTag(version: string): string {
  return version.startsWith('v') ? version : `v${version}`;
}

export function buildUserFacingRelease(input: {
  tag: string;
  body: string;
  publishedAt?: string | null;
  url?: string | null;
  includeDevSections?: boolean;
}): UserFacingRelease {
  const version = tagToVersion(input.tag);
  const rows = parseReleaseMarkdownBody(input.body);
  const sections = buildUserFacingSections(rows, {
    includeDevSections: input.includeDevSections,
  });
  return {
    version,
    tag: input.tag,
    publishedAt: input.publishedAt ?? null,
    url: input.url ?? null,
    summary: summarizeRelease(sections),
    sections,
  };
}
