import { describe, it, expect, beforeAll } from 'vitest';
import type supertest from 'supertest';
import { getRequest, createSession } from './helpers.js';

let request: supertest.Agent;

beforeAll(async () => {
  request = await getRequest();
}, 60_000);

async function newSessionId(): Promise<string> {
  const session = await createSession();
  return session.id as string;
}

describe('GET /api/sessions/:id/artifacts', () => {
  it('returns 404 for an unknown session', async () => {
    await request.get('/api/sessions/does-not-exist/artifacts').expect(404);
  });

  it('returns an empty list for a session with no artifacts', async () => {
    const id = await newSessionId();
    const res = await request.get(`/api/sessions/${id}/artifacts`).expect(200);
    expect(res.body).toEqual({ artifacts: [] });
  });
});

describe('POST /api/sessions/:id/artifacts', () => {
  it('uploads a document and lists / serves / deletes it', async () => {
    const id = await newSessionId();

    const upload = await request
      .post(`/api/sessions/${id}/artifacts`)
      .set('Content-Type', 'text/markdown')
      .set('x-filename', 'report.md')
      .set('x-agent-id', 'agent-hub-dev')
      .send(Buffer.from('# Report\n\nGenerated by the agent.'))
      .expect(200);

    expect(upload.body).toMatchObject({
      sessionId: id,
      filename: 'report.md',
      contentType: 'text/markdown',
      storageKind: 'local',
      createdBy: 'agent-hub-dev',
    });
    expect(upload.body.size).toBe(Buffer.from('# Report\n\nGenerated by the agent.').length);
    const artifactId = upload.body.id as string;
    expect(upload.body.url).toBe(`/api/sessions/${id}/artifacts/${artifactId}/content`);

    // List reflects the new artifact.
    const list = await request.get(`/api/sessions/${id}/artifacts`).expect(200);
    expect(list.body.artifacts).toHaveLength(1);
    expect(list.body.artifacts[0].id).toBe(artifactId);

    // Content round-trips — the agent can read the file back too.
    const content = await request
      .get(`/api/sessions/${id}/artifacts/${artifactId}/content`)
      .expect(200);
    expect(content.headers['content-type']).toContain('text/markdown');
    expect(content.headers['content-disposition']).toContain('inline');
    // Inert types still get the nosniff guard.
    expect(content.headers['x-content-type-options']).toBe('nosniff');
    expect(content.text).toBe('# Report\n\nGenerated by the agent.');

    // download=1 flips the disposition to attachment.
    const dl = await request
      .get(`/api/sessions/${id}/artifacts/${artifactId}/content?download=1`)
      .expect(200);
    expect(dl.headers['content-disposition']).toContain('attachment');

    // Delete removes it from the listing.
    await request.delete(`/api/sessions/${id}/artifacts/${artifactId}`).expect(200);
    const after = await request.get(`/api/sessions/${id}/artifacts`).expect(200);
    expect(after.body.artifacts).toHaveLength(0);
    await request.get(`/api/sessions/${id}/artifacts/${artifactId}/content`).expect(404);
  });

  it('accepts a JSON artifact despite the global JSON body parser', async () => {
    // Regression: the app mounts express.json() before the routes. Without the
    // upload-path skip, an application/json body is parsed into an object and
    // never reaches the route as a Buffer → 400 "Empty file body".
    const id = await newSessionId();
    const payload = '{"hello":"world","n":42}';
    const upload = await request
      .post(`/api/sessions/${id}/artifacts`)
      .set('Content-Type', 'application/json')
      .set('x-filename', 'data.json')
      // Identity serializer so superagent sends the raw bytes (like curl
      // --data-binary) instead of JSON-stringifying the Buffer for the
      // application/json content type.
      .serialize((v) => v)
      .send(Buffer.from(payload))
      .expect(200);
    expect(upload.body).toMatchObject({ filename: 'data.json', contentType: 'application/json' });
    expect(upload.body.size).toBe(Buffer.byteLength(payload));

    const content = await request
      .get(`/api/sessions/${id}/artifacts/${upload.body.id}/content`)
      .expect(200);
    expect(content.headers['content-type']).toContain('application/json');
    expect(content.text).toBe(payload);
  });

  it('rejects an empty body', async () => {
    const id = await newSessionId();
    await request
      .post(`/api/sessions/${id}/artifacts`)
      .set('Content-Type', 'application/octet-stream')
      .set('x-filename', 'empty.bin')
      .send(Buffer.alloc(0))
      .expect(400);
  });

  it('rejects an executable binary', async () => {
    const id = await newSessionId();
    // ELF magic: 0x7f 'E' 'L' 'F'
    const elf = Buffer.from([0x7f, 0x45, 0x4c, 0x46, 0x01, 0x02, 0x03, 0x04]);
    const res = await request
      .post(`/api/sessions/${id}/artifacts`)
      .set('Content-Type', 'application/octet-stream')
      .set('x-filename', 'malware')
      .send(elf)
      .expect(400);
    expect(res.body.error).toMatch(/executable|binary/i);
  });

  it('returns 404 uploading to an unknown session', async () => {
    await request
      .post('/api/sessions/nope/artifacts')
      .set('Content-Type', 'text/plain')
      .set('x-filename', 'x.txt')
      .send(Buffer.from('hi'))
      .expect(404);
  });

  it('appends an extension derived from the content type when the name has none', async () => {
    const id = await newSessionId();
    const upload = await request
      .post(`/api/sessions/${id}/artifacts`)
      .set('Content-Type', 'application/pdf')
      .set('x-filename', 'Quarterly Report')
      .send(Buffer.from('%PDF-1.4 fake pdf bytes'))
      .expect(200);
    expect(upload.body.filename).toBe('Quarterly Report.pdf');
  });

  it('defaults an omitted filename to artifact.<ext> from the content type', async () => {
    const id = await newSessionId();
    const upload = await request
      .post(`/api/sessions/${id}/artifacts`)
      .set('Content-Type', 'text/markdown')
      // no x-filename header at all
      .send(Buffer.from('# notes'))
      .expect(200);
    expect(upload.body.filename).toBe('artifact.md');
  });

  it('keeps the extension when the name is capped at the 255-char limit', async () => {
    const id = await newSessionId();
    // A 255-char extensionless name: a naive slice(0,255) after appending
    // ".pdf" would slice the suffix back off. The stored name must still end
    // in .pdf and stay within the column limit.
    const upload = await request
      .post(`/api/sessions/${id}/artifacts`)
      .set('Content-Type', 'application/pdf')
      .set('x-filename', 'a'.repeat(255))
      .send(Buffer.from('%PDF-1.4 fake pdf bytes'))
      .expect(200);
    expect(upload.body.filename.length).toBeLessThanOrEqual(255);
    expect(upload.body.filename.endsWith('.pdf')).toBe(true);
  });

  it('leaves an already-extensioned filename untouched', async () => {
    const id = await newSessionId();
    const upload = await request
      .post(`/api/sessions/${id}/artifacts`)
      .set('Content-Type', 'application/json')
      .set('x-filename', 'data.json')
      .serialize((v) => v)
      .send(Buffer.from('{"a":1}'))
      .expect(200);
    expect(upload.body.filename).toBe('data.json');
  });

  it('serves active content (HTML) as a neutralized attachment, never inline', async () => {
    const id = await newSessionId();
    const upload = await request
      .post(`/api/sessions/${id}/artifacts`)
      .set('Content-Type', 'text/html')
      .set('x-filename', 'evil.html')
      .send(Buffer.from('<script>alert(document.cookie)</script>'))
      .expect(200);
    const artifactId = upload.body.id as string;

    // Even with no ?download=1, HTML must come back as an attachment with a
    // neutral content type + nosniff so it can't execute in the app origin.
    const res = await request
      .get(`/api/sessions/${id}/artifacts/${artifactId}/content`)
      .expect(200);
    expect(res.headers['content-disposition']).toContain('attachment');
    expect(res.headers['content-type']).toContain('application/octet-stream');
    expect(res.headers['content-type']).not.toContain('text/html');
    expect(res.headers['x-content-type-options']).toBe('nosniff');
  });

  it('serves SVG (scriptable) as a neutralized attachment', async () => {
    const id = await newSessionId();
    const upload = await request
      .post(`/api/sessions/${id}/artifacts`)
      .set('Content-Type', 'image/svg+xml')
      .set('x-filename', 'logo.svg')
      .send(Buffer.from('<svg xmlns="http://www.w3.org/2000/svg"><script>1</script></svg>'))
      .expect(200);
    const artifactId = upload.body.id as string;
    const res = await request
      .get(`/api/sessions/${id}/artifacts/${artifactId}/content`)
      .expect(200);
    expect(res.headers['content-disposition']).toContain('attachment');
    expect(res.headers['content-type']).toContain('application/octet-stream');
    expect(res.headers['x-content-type-options']).toBe('nosniff');
  });
});

describe('GET /api/sessions/:id/artifacts/:artifactId/content', () => {
  it('returns 404 for an unknown artifact', async () => {
    const id = await newSessionId();
    await request.get(`/api/sessions/${id}/artifacts/missing/content`).expect(404);
  });

  // Regression: a filename with a non-ASCII char (em-dash) used to leak a raw
  // non-Latin1 byte into the Content-Disposition header, which reset the HTTP
  // stream (ERR_INVALID_CHAR) and surfaced in the browser as "Failed to fetch".
  it('serves a Unicode filename via RFC 5987 filename* without breaking download', async () => {
    const id = await newSessionId();
    const unicodeName = 'AH-1401 surveytracker scrub — patch (v1).diff';
    // Clients percent-encode X-Filename (a raw em-dash is rejected by the HTTP
    // stack as an invalid header char); the server decodes it back.
    const upload = await request
      .post(`/api/sessions/${id}/artifacts`)
      .set('Content-Type', 'text/plain')
      .set('x-filename', encodeURIComponent(unicodeName))
      .send(Buffer.from('diff --git a b\n'))
      .expect(200);
    const artifactId = upload.body.id as string;
    // Server decoded the header back to the real Unicode name.
    expect(upload.body.filename).toBe(unicodeName);

    // The download must succeed (200) — not reset the stream.
    const res = await request
      .get(`/api/sessions/${id}/artifacts/${artifactId}/content?download=1`)
      .expect(200);
    const cd = res.headers['content-disposition'] as string;
    expect(cd).toContain('attachment');
    // ASCII fallback: non-ASCII replaced, quotes/backslashes safe, header is Latin-1 clean.
    expect(cd).toMatch(/filename="[\x20-\x7e]+"/);
    // eslint-disable-next-line no-control-regex
    expect(/[^\x00-\xff]/.test(cd)).toBe(false);
    // RFC 5987 param carries the real UTF-8 name (em-dash = %E2%80%94).
    expect(cd).toContain("filename*=UTF-8''");
    expect(cd).toContain('%E2%80%94');
    expect(res.text).toBe('diff --git a b\n');
  });

  // ASCII-only names must NOT gain a redundant filename* parameter.
  it('omits filename* for a plain ASCII filename', async () => {
    const id = await newSessionId();
    const upload = await request
      .post(`/api/sessions/${id}/artifacts`)
      .set('Content-Type', 'text/plain')
      .set('x-filename', 'plain.txt')
      .send(Buffer.from('hi'))
      .expect(200);
    const res = await request
      .get(`/api/sessions/${id}/artifacts/${upload.body.id}/content?download=1`)
      .expect(200);
    const cd = res.headers['content-disposition'] as string;
    expect(cd).toContain('filename="plain.txt"');
    expect(cd).not.toContain('filename*');
  });
});
